// 中英文分类映射（供内容中心下拉筛选与结果卡片共用）

// Modrinth slug → 中文
export const CN_CATS: Record<string, string> = {
  fabric: "Fabric",
  forge: "Forge",
  neoforge: "NeoForge",
  quilt: "Quilt",
  optimization: "优化",
  library: "库 / API",
  utility: "实用",
  adventure: "冒险",
  magic: "魔法",
  tech: "科技",
  decoration: "装饰",
  equipment: "装备",
  food: "食物",
  misc: "杂项",
  mobs: "生物",
  storage: "存储",
  worldgen: "世界生成",
  challenge: "挑战",
  combat: "战斗",
  hardcore: "硬核",
  "mini-game": "小游戏",
  multiplayer: "多人联机",
  pvp: "PvP",
  "vanilla-plus": "原版增强",
  "16x": "16x",
  "32x": "32x",
  "64x": "64x",
  "128x": "128x",
  "256x": "256x",
  "512x": "512x",
  faithful: "Faithful",
  cursed: "Cursed",
  modern: "现代",
  "semi-realistic": "半写实",
  simplistic: "简约",
  themed: "主题",
  potato: "土豆画质",
  low: "低配",
  medium: "中配",
  high: "高配",
  ultra: "极限",
  "path-tracing": "光追",
  complementary: "Complementary",
  realistic: "写实",
  // 更多 Modrinth 分类
  armor: "盔甲",
  atmosphere: "氛围",
  cosmetic: "装饰外观",
  difficulty: "难度",
  economy: "经济",
  "game-mechanics": "游戏机制",
  gameplay: "玩法",
  management: "管理",
  performance: "性能",
  physics: "物理",
  redstone: "红石",
  "server-utility": "服务器工具",
  social: "社交",
  technology: "科技",
  tweaks: "微调",
  translation: "本地化",
  locale: "本地化",
  animated: "动态",
  model: "模型",
  entity: "实体",
  gui: "界面",
  font: "字体",
  "3d": "3D",
  hud: "HUD",
  texture: "材质",
  traditional: "传统",
  cartoon: "卡通",
  photorealism: "写实",
  vanilla: "原版",
  simple: "简约",
  ancient: "远古",
  fancy: "精致",
  medieval: "中世纪",
  blend: "混合",
  connect: "连接纹理",
  tileable: "无缝",
  fantasy: "奇幻",
  nostalgic: "怀旧",
  "48x": "48x",
  "512x+": "512x+",
  "8x-": "8x-",
  "adventure-mode": "冒险模式",
  anarchy: "无政府",
  audio: "音频",
  "battle-royale": "大逃杀",
  bedwars: "起床战争",
  blocks: "方块",
  bloom: "泛光",
  bosses: "Boss 战",
  challenging: "挑战",
  classes: "职业",
  "colored-lighting": "彩色光照",
  competitive: "竞技",
  "core-shaders": "核心着色器",
  "creative-mode": "创造模式",
  "creator-community": "创作者社区",
  crossplay: "跨平台",
  "custom-content": "自定义内容",
  dungeons: "地牢",
  entities: "实体",
  environment: "环境",
  factions: "阵营",
  foliage: "植被",
  fonts: "字体",
  gens: "生成器",
  "hardcore-mode": "极限模式",
  items: "物品",
  "keep-inventory": "保留物品栏",
  "kitchen-sink": "水槽",
  kitpvp: "套装 PvP",
  lifesteal: "生命窃取",
  lightweight: "轻量",
  media: "媒体",
  microgames: "微型游戏",
  minigame: "小游戏",
  minigames: "小游戏",
  mmo: "MMO",
  modded: "模组适配",
  models: "模型",
  network: "网络",
  "offline-mode": "离线模式",
  oneblock: "单方块",
  op: "OP",
  parkour: "跑酷",
  pbr: "PBR",
  "personal-worlds": "个人世界",
  plots: "地皮",
  pokemon: "宝可梦",
  prison: "监狱",
  pve: "PvE",
  questing: "任务",
  quests: "任务",
  racing: "赛车",
  "recording-smp": "录制型 SMP",
  reflections: "反射",
  roleplay: "角色扮演",
  rpg: "RPG",
  screenshot: "仅供截图",
  shadows: "阴影",
  skyblock: "空岛生存",
  smp: "SMP",
  teams: "团队",
  technical: "技术性",
  towns: "城镇",
  transportation: "交通",
  "vanilla-like": "原版风格",
  whitelisted: "需要白名单",
  "world-resets": "世界重置",
};

// CurseForge 英文分类名 → 中文
export const CN_CF_CATS: Record<string, string> = {
  adventure: "冒险",
  "adventure and rpg": "冒险与 RPG",
  "adventure and exploration": "冒险与探索",
  "challenge and exploration": "挑战与探索",
  magic: "魔法",
  tech: "科技",
  decoration: "装饰",
  equipment: "装备",
  food: "食物",
  misc: "杂项",
  mobs: "生物",
  storage: "存储",
  worldgen: "世界生成",
  "world generation": "世界生成",
  "api and library": "支持库与 API",
  "abstraction library": "抽象库",
  library: "支持库与 API",
  optimization: "优化",
  performance: "性能优化",
  "server utility": "服务器工具",
  utility: "实用",
  "utility and quality of life": "实用与生活质量",
  "armor, tools, and weapons": "盔甲、工具与武器",
  "astral sorcery": "星辉魔法",
  "audio, video": "音频、视频",
  biomes: "生物群系",
  "blood magic": "血魔法",
  botany: "植物学",
  buildcraft: "建筑工艺",
  chemistry: "化学",
  cooking: "烹饪",
  cosmetics: "装饰外观",
  dimensions: "维度",
  energy: "能源",
  "farming and food": "农业与食物",
  forestry: "林业",
  genetics: "遗传学",
  horses: "马匹",
  "industrial craft": "工业时代",
  mcreator: "MCreator",
  redstone: "红石",
  thaumcraft: "神秘时代",
  "tinker's construct": "匠魂",
  transport: "运输",
  tweaks: "微调",
  "world gen": "世界生成",
  miscellaneous: "杂项",
  addons: "附加内容",
  capes: "披风",
  customization: "自定义",
  "game mechanic": "游戏机制",
  "map and information": "地图与信息",
  social: "社交",
  "combat and pvp": "战斗与 PvP",
  hardcore: "硬核",
  minigame: "小游戏",
  pve: "PvE",
  pvp: "PvP",
  "quality of life": "生活品质",
  roleplaying: "角色扮演",
  "simple and clean": "简约清爽",
  themed: "主题",
  "photo realistic": "照片写实",
  "semi-realistic": "半写实",
  cartoon: "卡通",
  "sci-fi": "科幻",
  medieval: "中世纪",
  modern: "现代",
  anime: "动漫",
  cursed: "Cursed",
  faithful: "Faithful",
  "high resolution": "高分辨率",
  "low resolution": "低分辨率",
  pbr: "PBR",
  "potato graphics": "土豆画质",
  shader: "光影",
  // 更多 CurseForge 分类（含分辨率的英文叫法）
  sixteen: "16x",
  "thirty two": "32x",
  "sixty four": "64x",
  "one hundred twenty eight": "128x",
  "two hundred fifty six": "256x",
  "five hundred twelve": "512x",
  "one thousand twenty four": "1024x",
  traditional: "传统",
  theme: "主题",
  simple: "简约",
  gui: "界面",
  font: "字体",
  hud: "HUD",
  "3d": "3D",
  animated: "动态",
  model: "模型",
  entity: "实体",
  compatibility: "兼容",
  compat: "兼容",
  bugfix: "修复",
  weapon: "武器",
  armor: "盔甲",
  "one-click": "一键安装",
  skybox: "天空盒",
  "mini game": "小游戏",
  "full hd": "全高清",
  "game-like": "游戏风格",
  fog: "雾效",
  solid: "纯色",
  movie: "电影",
  "path tracing": "光追",
  ultra: "极限",
  "colored lighting": "彩色光照",
  "clean and simple": "简约清爽",
  lightweight: "轻量",
};

/** CurseForge 英文分类名 → 中文（未命中回退原名） */
export function cnCfName(name: string): string {
  return CN_CF_CATS[name.toLowerCase()] ?? name;
}

/** 通用分类翻译：Modrinth slug / CurseForge 英文名 → 中文（未命中回退原值） */
export function translateCategory(c: string): string {
  if (!c) return c;
  return CN_CATS[c] ?? CN_CF_CATS[c.toLowerCase()] ?? c;
}
